export interface ActionI {
  type: string;
  payload: any;
}

export default {
  SET_THEME_REDUCER: "SET_THEME_REDUCER",
  SET_THEME_NAME: "SET_THEME_NAME",
  SET_THEME: "SET_THEME",

  SET_NOTIFICATIONS: "SET_NOTIFICATIONS",
  ADD_NOTIFICATIONS: "ADD_NOTIFICATIONS",

  ADD_ACCOUNT: "SET_ACCOUNT",
  DELETE_ACCOUNT: "DELETE_ACCOUNT",
};
