export interface ActionI<T> {
  type: string;
  payload: T;
}

export default {
  SET_THEME_REDUCER: "SET_THEME_REDUCER",
  SET_THEME_NAME: "SET_THEME_NAME",
  SET_THEME: "SET_THEME",

  SET_NOTIFICATIONS: "SET_NOTIFICATIONS",
  ADD_NOTIFICATIONS: "ADD_NOTIFICATIONS",
  SET_NOTIFICATION_READ: "SET_NOTIFICATION_READ",

  SET_ACTIVE_ACCOUNTS: "SET_ACTIVE_ACCOUNTS",
  UNSET_ACTIVE_ACCOUNT: "UNSET_ACTIVE_ACCOUNT",

  SET_ACCOUNTS: "SET_ACCOUNTS",
  ADD_ACCOUNT: "SET_ACCOUNT",
  DELETE_ACCOUNT: "DELETE_ACCOUNT",
  ADD_ACCUNT_PROPERTY: "ADD_ACCUNT_PROPERTY",
  ADD_METER_NUMBER: "ADD_METER_NUMBER",

  SET_COST_PER_LITRE: "SET_COST_PER_LITRE",

  SET_PAY_POINTS: "SET_PAY_POINTS",
  ADD_PAYPOINT: "ADD_PAYPOINT",

  SET_PAYMENT_HISTORY: "SET_PAYMENT_HISTORY",
  ADD_PAYMENT_HISTORY: "ADD_PAYMENT_HISTORY",

  SET_USER_REDUCER: 'SET_USER_REDUCER',
  SET_MAN_NUMBER: "SET_MAN_NUMBER",
  SET_USERNAME: "SET_USERNAME",
  UNSET_USERNAME: "UNSET_USERNAME",
  UNSET_MAN_NUMBER: "UNSET_MAN_NUMBER",
  SET_USER_TOKEN: "SET_USER_TOKEN",
  DELETE_USER_TOKEN: 'DELETE_USER_TOKEN',

  SET_SERVICE_TYPES: "SET_SERVICE_TYPES",

  SET_BILL_GROUP: "SET_BILL_GROUP",
  ADD_BILL_GROUP: "ADD_BILL_GROUP",
  DELETE_BILL_GROUP: "DELETE_BILL_GROUP",

  SET_BOOK_NUMBER: "SET_BOOK_NUMBER",
  ADD_BOOK_NUMBER: "ADD_BOOK_NUMBER",
  DELETE_BOOK_NUMBER: "DELETE_BOOK_NUMBER",

  SET_MR_PROPERTY: "SET_MR_PROPERTY",
  ADD_MR_PROPERTY: "ADD_MR_PROPERTY",
  DELETE_MR_PROPERTY: "DELETE_MR_PROPERTY",

  SET_ACCESS_NOTES: "SET_ACCESS_NOTES",
  SET_AN_NOTES: "SET_AN_NOTES",
  SET_AN_ACCESS: "SET_AN_ACCESS",

  SET_PUSH_TOKEN_SUBMITTED: "SET_PUSH_TOKEN_SUBMITTTED",
};
